### ISSUE TITLE
Configurable custom emojis

### ISSUE THREAD

**Issue by Galarzaa90** [Galarzaa90/NabBot#101]
As some may know, all bots have the privilege of using emojis from any server they're in, like they had Nitro. 

I want to add an emoji entry to `config.yml` where you can add entries for certain emojis.

```yml
emoji:
    - levelup: 🌟
    - death: ☠️
    - deathplayer: 💀
    - druid: ❄️
    - sorcerer: 🔥
    - paladin: 🏹
    - knight: 🛡️
    - checkmark: "<:greencheck:448645325918437376>"
    - cross: "<:redcheck:448645341659791360>"
```

In this case, checkmarks and crosses use a custom emoji, :greencheck: and :redcheck: respectively.

It's recommended to add NabBot to a server just for the custom emojis, to avoid changing the shortcuts, as they would break the reference.
